name: Pre-Release (dev)

on:
  push:
    branches: [dev]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/kiosk-dev .

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-$(date +%s)
          name: "Pre-release from dev ($(date +%Y-%m-%d))"
          files: dist/kiosk-dev
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}