name: Pre-Release (dev)

on:
  push:
    branches: [dev]

jobs:
  build-and-pre-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run Tests
        run: go test ./...

      - name: Build
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/kiosk-dev .

      - name: Create Git tag
        run: |
          git config user.name "kiosk bot"
          git config user.email "actions@github.com"
          tag="dev-$(date +%s)"
          git tag $tag
          git push origin $tag
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Pre-release from dev"
          files: dist/kiosk-dev
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}