name: Pre-Release (dev)

on:
  push:
    branches: [dev]

jobs:
  pre-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git Tag
        env:
          PAT: ${{ secrets.PAT_FOR_RELEASE }}
        run: |
          git config --global user.name "kiosk bot"
          git config --global user.email "actions@github.com"
          tag="dev-$(date +%s)"
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

      - name: Package Source Code
        run: |
          git archive --format=tar.gz --prefix="kiosk-${{ env.TAG_NAME }}/" HEAD > "kiosk-${{ env.TAG_NAME }}.tar.gz"

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Pre-release from dev"
          files: kiosk-${{ env.TAG_NAME }}.tar.gz
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}