name: Release (main)

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/kiosk .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: main-$(date +%s)
          name: "kiosk build from main ($(date +%Y-%m-%d))"
          files: dist/kiosk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}