name: Release (main)

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package Source Code
        run: |
          git archive --format=tar.gz --prefix="kiosk-${{ github.sha }}/" HEAD > "kiosk-${{ github.sha }}.tar.gz"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          name: "Release ${{ github.sha }}"
          files: kiosk-${{ github.sha }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}