name: Release (main)

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git Tag
        env:
          PAT: ${{ secrets.PAT_FOR_RELEASE }}
        run: |
          git config --global user.name "kiosk bot"
          git config --global user.email "actions@github.com"
          tag="main-$(date +%s)"
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

      - name: Package Source Code
        run: |
          git archive --format=tar.gz --prefix="kiosk-${{ env.TAG_NAME }}/" HEAD > "kiosk-${{ env.TAG_NAME }}.tar.gz"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release from main"
          files: kiosk-${{ env.TAG_NAME }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_RELEASE }}