name: Release (main)

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run Tests
        run: go test ./...

      - name: Build
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/kiosk .

      - name: Create Git tag
        env:
          PAT: ${{ secrets.PAT_FOR_RELEASE }}
        run: |
          git config user.name "kiosk bot"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          tag="main-$(date +%s)"
          git tag $tag
          git push origin $tag
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "kiosk build from main ($(date +%Y-%m-%d))"
          files: dist/kiosk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}